//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Inputs/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Default"",
            ""id"": ""4e727e32-6daf-44e9-89ea-f99f5487cba0"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""3641c83b-d93b-4569-b73d-bff5b71963b0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Camera"",
                    ""type"": ""Value"",
                    ""id"": ""da490561-0853-4e7d-ba28-bdf57a98738c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LayBomb"",
                    ""type"": ""Button"",
                    ""id"": ""ea4271b3-2fac-4890-a629-513dc3f0cf68"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""5e5fa03e-d00d-43f5-9906-4b6986a16543"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenMenu"",
                    ""type"": ""Button"",
                    ""id"": ""5a98aac5-7c05-4a87-8571-2b2198d7006d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Detonate"",
                    ""type"": ""Button"",
                    ""id"": ""bed54b2b-3b6e-4fac-b899-d2819f42c9c8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""f6ae2534-5d31-4258-99cd-ccc14880cf26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PickUp"",
                    ""type"": ""Button"",
                    ""id"": ""01850bfb-fe78-44bf-9b8a-95b76f4ab906"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PreviousBombType"",
                    ""type"": ""Button"",
                    ""id"": ""02dfb883-648d-400e-9863-cec6cd338300"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextBombType"",
                    ""type"": ""Button"",
                    ""id"": ""2e89a318-455a-443d-95de-d8d57e6861fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fdc2b5f8-7aa5-44db-a411-83007c4942fe"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": ""Controller"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""a3fdfb28-00e1-4a54-85f1-6193121cf9d0"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2e778e5b-c340-4007-807b-8b67680e35f9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b1c4975a-46b4-4feb-a065-28baa57a687a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""10de1a88-7100-4068-8e4a-144587dd2669"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""75c4ddaa-52f9-421e-b37c-1e7689110f89"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e091ebcc-2008-4afe-87d2-c7bab13e929b"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2afd9813-b92f-4c04-9cb6-ab2ed094958f"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""LayBomb"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2bed6ebb-fcea-4299-aabf-edf74ac610fe"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""LayBomb"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""17d6c2ac-ec47-414f-8d38-ec3fed4112f5"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""809f32de-3e87-4944-969e-a00df613687a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15053b6b-1441-4e9c-bba5-28c1e9a52d3e"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""OpenMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c6236b8-64c7-4988-8371-7ba86b3c4135"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""OpenMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d34b4154-e18a-48f7-89bd-7b5aab27e4a3"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Detonate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ddfc6bb7-3bca-45a0-a212-63c7b560159d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Detonate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8c95812-3b81-49ba-b6c5-0cd74bf0c0e4"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07a919b8-fcad-4e4b-a840-939220511cfc"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd818bfe-6cdc-40bf-a5b6-5b913b670019"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83502a58-b591-4ce4-af6a-42192b0732f5"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PickUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b4f8e6c-ad60-4337-9a20-322ec65f5cf7"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PickUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6fc4bcf8-b10a-437e-b4bb-7b0a635415b7"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PreviousBombType"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf10617a-683b-4253-883b-94a4d3ed9059"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PreviousBombType"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8daa9fc7-8b43-463c-8ae9-4df45fab84ee"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextBombType"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2ce4d0f-7d95-466a-9040-ea923349ca2a"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextBombType"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Editor"",
            ""id"": ""a9a332f4-d43c-41d9-9c25-c92e3929dcf2"",
            ""actions"": [
                {
                    ""name"": ""MoveXZ"",
                    ""type"": ""Value"",
                    ""id"": ""a8cfcb31-168d-42ab-9d70-ae447d320065"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveUp"",
                    ""type"": ""Button"",
                    ""id"": ""8b7acc03-f899-47c2-866a-db4d6d16e4d4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveDown"",
                    ""type"": ""Button"",
                    ""id"": ""71acd06d-efe7-49c9-b35d-0cbc02e8b1eb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PreviousTile"",
                    ""type"": ""Button"",
                    ""id"": ""05aa22ca-6d1c-499d-9a9f-d28ab2270488"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextTile"",
                    ""type"": ""Button"",
                    ""id"": ""23002da1-b65e-4349-b466-56523b36df7c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaceTile"",
                    ""type"": ""Button"",
                    ""id"": ""0d07b155-ca8a-4ae6-bdfa-baa5f0e336e4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SaveMenu"",
                    ""type"": ""Button"",
                    ""id"": ""e63f1955-bf65-40f2-877e-9140711a31d1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HelpMenu"",
                    ""type"": ""Button"",
                    ""id"": ""6c179d0e-875f-4531-9951-54f1c4b86a7c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateCamera"",
                    ""type"": ""Value"",
                    ""id"": ""40dc5a54-0d28-42fb-84b1-a9e9e26bd26e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseRotateCameraClick"",
                    ""type"": ""Button"",
                    ""id"": ""c6116b32-88e6-4684-9c54-4a18ce5d5432"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseRotateCameraDrag"",
                    ""type"": ""Value"",
                    ""id"": ""5e044419-29c1-43a2-b967-1afea171f1d8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PropertiesMenu"",
                    ""type"": ""Button"",
                    ""id"": ""4c44fe3b-a742-4ccb-9f9c-b5d2097d4b7f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DisableMouseMove"",
                    ""type"": ""Button"",
                    ""id"": ""883fa8ae-9206-4e5c-9366-bbaaa65bd496"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseWheelMove"",
                    ""type"": ""Value"",
                    ""id"": ""26a8b5b8-03f5-4691-a956-71bd61ad2a7a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ResetCamera"",
                    ""type"": ""Button"",
                    ""id"": ""f8916540-3073-48d6-9df6-eeddff049c55"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3d9193fe-8d7b-406b-8aed-0bdbfaa3874c"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""MoveXZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WSAD"",
                    ""id"": ""fadf7924-4691-4cbe-95d9-49421f3f1130"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveXZ"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9a87e9db-3fdd-4719-b8b3-5b7a85dc12d4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""MoveXZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""41b7790d-7794-453f-8d8a-f3e856b1c09e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""MoveXZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8cee767d-344f-401e-a7be-ff831a20bee9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""MoveXZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""85e3b879-ea7b-4fd1-ba47-e81c2a7954ce"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""MoveXZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""24d0fca9-bd3c-4594-86f3-2afc95ee0694"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""MoveUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99165171-75e3-45d7-9c2f-0244ea7aa8a4"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""MoveUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0ec6779-ff56-4e92-84bc-2153ab3e7ace"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""MoveDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da3a4740-c34a-483e-be29-e79964f13aed"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""MoveDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0ce674e-8942-4031-8510-db2fa0ad2a54"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""PreviousTile"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3ab599b-8f9a-4dd9-aa44-cf4cb9982d8d"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""PreviousTile"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0797132-7b4d-4d20-8c82-bb904399f2fb"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""NextTile"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26a62501-c0bb-4d42-84ec-b3a39852c467"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""NextTile"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""adddb854-8762-495e-a4f7-db39fe971255"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""PlaceTile"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78b4510c-c6cc-4576-8366-6e79a70d8851"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""PlaceTile"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0907922c-4e24-46b6-9b63-ad69cfd850c3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceTile"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""074535b2-b3ac-4b1f-acd7-961a908d8549"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""SaveMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6bacf120-e2a8-4a41-af8d-1e20e284a1a2"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""SaveMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""340a7038-5927-4afe-991a-40cd45ff5b80"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""HelpMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c962d53-c3d5-47c2-8276-0c7dfef8dec7"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""HelpMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f134bcd-e0f3-4a69-bdc5-11b6892a3799"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a857e1f-f713-438e-b18d-15ac0ad11cf2"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""MouseRotateCameraDrag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0d83673-76be-460e-9cb8-1b9cbaf53ee5"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""PropertiesMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c564d2f-7e0a-4102-8f8e-397012e5ee21"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""PropertiesMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8390f66-e263-49d8-8e92-bcacf763363e"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""MouseRotateCameraClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39b27048-7a6d-4ca6-b25f-1c793630c32f"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DisableMouseMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21e2142a-cf18-4f92-a5c5-994f63647d79"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseWheelMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""deb8f812-490d-4970-b1da-9011909e8e47"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3428f09-a60d-4384-a96e-322b33be45f8"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Editor-SaveMenu"",
            ""id"": ""ec466d60-4cdc-4bed-b50c-67af856ea9b9"",
            ""actions"": [
                {
                    ""name"": ""Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""a9e65d2c-95a1-47ef-a3bc-0261ef68c646"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""14173443-e7c4-4484-8537-d039077101b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move Cursor"",
                    ""type"": ""Value"",
                    ""id"": ""9d6b3b54-f2f3-46ba-a20e-a17722f961ce"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""efe97afe-036b-4245-82d9-6652dfa9d152"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b14979dc-6508-4d8a-8155-4a18c4b19533"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e627616e-f9ff-47a6-9e86-29db9be681d2"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Move Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""ArrowKeys"",
                    ""id"": ""6d2c6896-b732-4a99-a886-f770697aad7a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""bce6eb56-76fd-466c-aa77-f49586ddb214"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1f548b3d-81d0-47eb-86b5-e27bd6e3a318"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""024ffe5d-3687-493d-bd38-d16a76283403"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""240032de-385a-4115-aff8-3c859d0e619c"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KeyboardMouse"",
            ""bindingGroup"": ""KeyboardMouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Controller"",
            ""bindingGroup"": ""Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Default
        m_Default = asset.FindActionMap("Default", throwIfNotFound: true);
        m_Default_Movement = m_Default.FindAction("Movement", throwIfNotFound: true);
        m_Default_Camera = m_Default.FindAction("Camera", throwIfNotFound: true);
        m_Default_LayBomb = m_Default.FindAction("LayBomb", throwIfNotFound: true);
        m_Default_Jump = m_Default.FindAction("Jump", throwIfNotFound: true);
        m_Default_OpenMenu = m_Default.FindAction("OpenMenu", throwIfNotFound: true);
        m_Default_Detonate = m_Default.FindAction("Detonate", throwIfNotFound: true);
        m_Default_Run = m_Default.FindAction("Run", throwIfNotFound: true);
        m_Default_PickUp = m_Default.FindAction("PickUp", throwIfNotFound: true);
        m_Default_PreviousBombType = m_Default.FindAction("PreviousBombType", throwIfNotFound: true);
        m_Default_NextBombType = m_Default.FindAction("NextBombType", throwIfNotFound: true);
        // Editor
        m_Editor = asset.FindActionMap("Editor", throwIfNotFound: true);
        m_Editor_MoveXZ = m_Editor.FindAction("MoveXZ", throwIfNotFound: true);
        m_Editor_MoveUp = m_Editor.FindAction("MoveUp", throwIfNotFound: true);
        m_Editor_MoveDown = m_Editor.FindAction("MoveDown", throwIfNotFound: true);
        m_Editor_PreviousTile = m_Editor.FindAction("PreviousTile", throwIfNotFound: true);
        m_Editor_NextTile = m_Editor.FindAction("NextTile", throwIfNotFound: true);
        m_Editor_PlaceTile = m_Editor.FindAction("PlaceTile", throwIfNotFound: true);
        m_Editor_SaveMenu = m_Editor.FindAction("SaveMenu", throwIfNotFound: true);
        m_Editor_HelpMenu = m_Editor.FindAction("HelpMenu", throwIfNotFound: true);
        m_Editor_RotateCamera = m_Editor.FindAction("RotateCamera", throwIfNotFound: true);
        m_Editor_MouseRotateCameraClick = m_Editor.FindAction("MouseRotateCameraClick", throwIfNotFound: true);
        m_Editor_MouseRotateCameraDrag = m_Editor.FindAction("MouseRotateCameraDrag", throwIfNotFound: true);
        m_Editor_PropertiesMenu = m_Editor.FindAction("PropertiesMenu", throwIfNotFound: true);
        m_Editor_DisableMouseMove = m_Editor.FindAction("DisableMouseMove", throwIfNotFound: true);
        m_Editor_MouseWheelMove = m_Editor.FindAction("MouseWheelMove", throwIfNotFound: true);
        m_Editor_ResetCamera = m_Editor.FindAction("ResetCamera", throwIfNotFound: true);
        // Editor-SaveMenu
        m_EditorSaveMenu = asset.FindActionMap("Editor-SaveMenu", throwIfNotFound: true);
        m_EditorSaveMenu_Confirm = m_EditorSaveMenu.FindAction("Confirm", throwIfNotFound: true);
        m_EditorSaveMenu_Cancel = m_EditorSaveMenu.FindAction("Cancel", throwIfNotFound: true);
        m_EditorSaveMenu_MoveCursor = m_EditorSaveMenu.FindAction("Move Cursor", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Default
    private readonly InputActionMap m_Default;
    private IDefaultActions m_DefaultActionsCallbackInterface;
    private readonly InputAction m_Default_Movement;
    private readonly InputAction m_Default_Camera;
    private readonly InputAction m_Default_LayBomb;
    private readonly InputAction m_Default_Jump;
    private readonly InputAction m_Default_OpenMenu;
    private readonly InputAction m_Default_Detonate;
    private readonly InputAction m_Default_Run;
    private readonly InputAction m_Default_PickUp;
    private readonly InputAction m_Default_PreviousBombType;
    private readonly InputAction m_Default_NextBombType;
    public struct DefaultActions
    {
        private @PlayerControls m_Wrapper;
        public DefaultActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Default_Movement;
        public InputAction @Camera => m_Wrapper.m_Default_Camera;
        public InputAction @LayBomb => m_Wrapper.m_Default_LayBomb;
        public InputAction @Jump => m_Wrapper.m_Default_Jump;
        public InputAction @OpenMenu => m_Wrapper.m_Default_OpenMenu;
        public InputAction @Detonate => m_Wrapper.m_Default_Detonate;
        public InputAction @Run => m_Wrapper.m_Default_Run;
        public InputAction @PickUp => m_Wrapper.m_Default_PickUp;
        public InputAction @PreviousBombType => m_Wrapper.m_Default_PreviousBombType;
        public InputAction @NextBombType => m_Wrapper.m_Default_NextBombType;
        public InputActionMap Get() { return m_Wrapper.m_Default; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultActions set) { return set.Get(); }
        public void SetCallbacks(IDefaultActions instance)
        {
            if (m_Wrapper.m_DefaultActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnMovement;
                @Camera.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnCamera;
                @Camera.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnCamera;
                @Camera.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnCamera;
                @LayBomb.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnLayBomb;
                @LayBomb.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnLayBomb;
                @LayBomb.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnLayBomb;
                @Jump.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnJump;
                @OpenMenu.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnOpenMenu;
                @OpenMenu.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnOpenMenu;
                @OpenMenu.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnOpenMenu;
                @Detonate.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnDetonate;
                @Detonate.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnDetonate;
                @Detonate.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnDetonate;
                @Run.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnRun;
                @Run.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnRun;
                @Run.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnRun;
                @PickUp.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnPickUp;
                @PickUp.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnPickUp;
                @PickUp.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnPickUp;
                @PreviousBombType.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnPreviousBombType;
                @PreviousBombType.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnPreviousBombType;
                @PreviousBombType.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnPreviousBombType;
                @NextBombType.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnNextBombType;
                @NextBombType.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnNextBombType;
                @NextBombType.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnNextBombType;
            }
            m_Wrapper.m_DefaultActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Camera.started += instance.OnCamera;
                @Camera.performed += instance.OnCamera;
                @Camera.canceled += instance.OnCamera;
                @LayBomb.started += instance.OnLayBomb;
                @LayBomb.performed += instance.OnLayBomb;
                @LayBomb.canceled += instance.OnLayBomb;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @OpenMenu.started += instance.OnOpenMenu;
                @OpenMenu.performed += instance.OnOpenMenu;
                @OpenMenu.canceled += instance.OnOpenMenu;
                @Detonate.started += instance.OnDetonate;
                @Detonate.performed += instance.OnDetonate;
                @Detonate.canceled += instance.OnDetonate;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @PickUp.started += instance.OnPickUp;
                @PickUp.performed += instance.OnPickUp;
                @PickUp.canceled += instance.OnPickUp;
                @PreviousBombType.started += instance.OnPreviousBombType;
                @PreviousBombType.performed += instance.OnPreviousBombType;
                @PreviousBombType.canceled += instance.OnPreviousBombType;
                @NextBombType.started += instance.OnNextBombType;
                @NextBombType.performed += instance.OnNextBombType;
                @NextBombType.canceled += instance.OnNextBombType;
            }
        }
    }
    public DefaultActions @Default => new DefaultActions(this);

    // Editor
    private readonly InputActionMap m_Editor;
    private IEditorActions m_EditorActionsCallbackInterface;
    private readonly InputAction m_Editor_MoveXZ;
    private readonly InputAction m_Editor_MoveUp;
    private readonly InputAction m_Editor_MoveDown;
    private readonly InputAction m_Editor_PreviousTile;
    private readonly InputAction m_Editor_NextTile;
    private readonly InputAction m_Editor_PlaceTile;
    private readonly InputAction m_Editor_SaveMenu;
    private readonly InputAction m_Editor_HelpMenu;
    private readonly InputAction m_Editor_RotateCamera;
    private readonly InputAction m_Editor_MouseRotateCameraClick;
    private readonly InputAction m_Editor_MouseRotateCameraDrag;
    private readonly InputAction m_Editor_PropertiesMenu;
    private readonly InputAction m_Editor_DisableMouseMove;
    private readonly InputAction m_Editor_MouseWheelMove;
    private readonly InputAction m_Editor_ResetCamera;
    public struct EditorActions
    {
        private @PlayerControls m_Wrapper;
        public EditorActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveXZ => m_Wrapper.m_Editor_MoveXZ;
        public InputAction @MoveUp => m_Wrapper.m_Editor_MoveUp;
        public InputAction @MoveDown => m_Wrapper.m_Editor_MoveDown;
        public InputAction @PreviousTile => m_Wrapper.m_Editor_PreviousTile;
        public InputAction @NextTile => m_Wrapper.m_Editor_NextTile;
        public InputAction @PlaceTile => m_Wrapper.m_Editor_PlaceTile;
        public InputAction @SaveMenu => m_Wrapper.m_Editor_SaveMenu;
        public InputAction @HelpMenu => m_Wrapper.m_Editor_HelpMenu;
        public InputAction @RotateCamera => m_Wrapper.m_Editor_RotateCamera;
        public InputAction @MouseRotateCameraClick => m_Wrapper.m_Editor_MouseRotateCameraClick;
        public InputAction @MouseRotateCameraDrag => m_Wrapper.m_Editor_MouseRotateCameraDrag;
        public InputAction @PropertiesMenu => m_Wrapper.m_Editor_PropertiesMenu;
        public InputAction @DisableMouseMove => m_Wrapper.m_Editor_DisableMouseMove;
        public InputAction @MouseWheelMove => m_Wrapper.m_Editor_MouseWheelMove;
        public InputAction @ResetCamera => m_Wrapper.m_Editor_ResetCamera;
        public InputActionMap Get() { return m_Wrapper.m_Editor; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(EditorActions set) { return set.Get(); }
        public void SetCallbacks(IEditorActions instance)
        {
            if (m_Wrapper.m_EditorActionsCallbackInterface != null)
            {
                @MoveXZ.started -= m_Wrapper.m_EditorActionsCallbackInterface.OnMoveXZ;
                @MoveXZ.performed -= m_Wrapper.m_EditorActionsCallbackInterface.OnMoveXZ;
                @MoveXZ.canceled -= m_Wrapper.m_EditorActionsCallbackInterface.OnMoveXZ;
                @MoveUp.started -= m_Wrapper.m_EditorActionsCallbackInterface.OnMoveUp;
                @MoveUp.performed -= m_Wrapper.m_EditorActionsCallbackInterface.OnMoveUp;
                @MoveUp.canceled -= m_Wrapper.m_EditorActionsCallbackInterface.OnMoveUp;
                @MoveDown.started -= m_Wrapper.m_EditorActionsCallbackInterface.OnMoveDown;
                @MoveDown.performed -= m_Wrapper.m_EditorActionsCallbackInterface.OnMoveDown;
                @MoveDown.canceled -= m_Wrapper.m_EditorActionsCallbackInterface.OnMoveDown;
                @PreviousTile.started -= m_Wrapper.m_EditorActionsCallbackInterface.OnPreviousTile;
                @PreviousTile.performed -= m_Wrapper.m_EditorActionsCallbackInterface.OnPreviousTile;
                @PreviousTile.canceled -= m_Wrapper.m_EditorActionsCallbackInterface.OnPreviousTile;
                @NextTile.started -= m_Wrapper.m_EditorActionsCallbackInterface.OnNextTile;
                @NextTile.performed -= m_Wrapper.m_EditorActionsCallbackInterface.OnNextTile;
                @NextTile.canceled -= m_Wrapper.m_EditorActionsCallbackInterface.OnNextTile;
                @PlaceTile.started -= m_Wrapper.m_EditorActionsCallbackInterface.OnPlaceTile;
                @PlaceTile.performed -= m_Wrapper.m_EditorActionsCallbackInterface.OnPlaceTile;
                @PlaceTile.canceled -= m_Wrapper.m_EditorActionsCallbackInterface.OnPlaceTile;
                @SaveMenu.started -= m_Wrapper.m_EditorActionsCallbackInterface.OnSaveMenu;
                @SaveMenu.performed -= m_Wrapper.m_EditorActionsCallbackInterface.OnSaveMenu;
                @SaveMenu.canceled -= m_Wrapper.m_EditorActionsCallbackInterface.OnSaveMenu;
                @HelpMenu.started -= m_Wrapper.m_EditorActionsCallbackInterface.OnHelpMenu;
                @HelpMenu.performed -= m_Wrapper.m_EditorActionsCallbackInterface.OnHelpMenu;
                @HelpMenu.canceled -= m_Wrapper.m_EditorActionsCallbackInterface.OnHelpMenu;
                @RotateCamera.started -= m_Wrapper.m_EditorActionsCallbackInterface.OnRotateCamera;
                @RotateCamera.performed -= m_Wrapper.m_EditorActionsCallbackInterface.OnRotateCamera;
                @RotateCamera.canceled -= m_Wrapper.m_EditorActionsCallbackInterface.OnRotateCamera;
                @MouseRotateCameraClick.started -= m_Wrapper.m_EditorActionsCallbackInterface.OnMouseRotateCameraClick;
                @MouseRotateCameraClick.performed -= m_Wrapper.m_EditorActionsCallbackInterface.OnMouseRotateCameraClick;
                @MouseRotateCameraClick.canceled -= m_Wrapper.m_EditorActionsCallbackInterface.OnMouseRotateCameraClick;
                @MouseRotateCameraDrag.started -= m_Wrapper.m_EditorActionsCallbackInterface.OnMouseRotateCameraDrag;
                @MouseRotateCameraDrag.performed -= m_Wrapper.m_EditorActionsCallbackInterface.OnMouseRotateCameraDrag;
                @MouseRotateCameraDrag.canceled -= m_Wrapper.m_EditorActionsCallbackInterface.OnMouseRotateCameraDrag;
                @PropertiesMenu.started -= m_Wrapper.m_EditorActionsCallbackInterface.OnPropertiesMenu;
                @PropertiesMenu.performed -= m_Wrapper.m_EditorActionsCallbackInterface.OnPropertiesMenu;
                @PropertiesMenu.canceled -= m_Wrapper.m_EditorActionsCallbackInterface.OnPropertiesMenu;
                @DisableMouseMove.started -= m_Wrapper.m_EditorActionsCallbackInterface.OnDisableMouseMove;
                @DisableMouseMove.performed -= m_Wrapper.m_EditorActionsCallbackInterface.OnDisableMouseMove;
                @DisableMouseMove.canceled -= m_Wrapper.m_EditorActionsCallbackInterface.OnDisableMouseMove;
                @MouseWheelMove.started -= m_Wrapper.m_EditorActionsCallbackInterface.OnMouseWheelMove;
                @MouseWheelMove.performed -= m_Wrapper.m_EditorActionsCallbackInterface.OnMouseWheelMove;
                @MouseWheelMove.canceled -= m_Wrapper.m_EditorActionsCallbackInterface.OnMouseWheelMove;
                @ResetCamera.started -= m_Wrapper.m_EditorActionsCallbackInterface.OnResetCamera;
                @ResetCamera.performed -= m_Wrapper.m_EditorActionsCallbackInterface.OnResetCamera;
                @ResetCamera.canceled -= m_Wrapper.m_EditorActionsCallbackInterface.OnResetCamera;
            }
            m_Wrapper.m_EditorActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MoveXZ.started += instance.OnMoveXZ;
                @MoveXZ.performed += instance.OnMoveXZ;
                @MoveXZ.canceled += instance.OnMoveXZ;
                @MoveUp.started += instance.OnMoveUp;
                @MoveUp.performed += instance.OnMoveUp;
                @MoveUp.canceled += instance.OnMoveUp;
                @MoveDown.started += instance.OnMoveDown;
                @MoveDown.performed += instance.OnMoveDown;
                @MoveDown.canceled += instance.OnMoveDown;
                @PreviousTile.started += instance.OnPreviousTile;
                @PreviousTile.performed += instance.OnPreviousTile;
                @PreviousTile.canceled += instance.OnPreviousTile;
                @NextTile.started += instance.OnNextTile;
                @NextTile.performed += instance.OnNextTile;
                @NextTile.canceled += instance.OnNextTile;
                @PlaceTile.started += instance.OnPlaceTile;
                @PlaceTile.performed += instance.OnPlaceTile;
                @PlaceTile.canceled += instance.OnPlaceTile;
                @SaveMenu.started += instance.OnSaveMenu;
                @SaveMenu.performed += instance.OnSaveMenu;
                @SaveMenu.canceled += instance.OnSaveMenu;
                @HelpMenu.started += instance.OnHelpMenu;
                @HelpMenu.performed += instance.OnHelpMenu;
                @HelpMenu.canceled += instance.OnHelpMenu;
                @RotateCamera.started += instance.OnRotateCamera;
                @RotateCamera.performed += instance.OnRotateCamera;
                @RotateCamera.canceled += instance.OnRotateCamera;
                @MouseRotateCameraClick.started += instance.OnMouseRotateCameraClick;
                @MouseRotateCameraClick.performed += instance.OnMouseRotateCameraClick;
                @MouseRotateCameraClick.canceled += instance.OnMouseRotateCameraClick;
                @MouseRotateCameraDrag.started += instance.OnMouseRotateCameraDrag;
                @MouseRotateCameraDrag.performed += instance.OnMouseRotateCameraDrag;
                @MouseRotateCameraDrag.canceled += instance.OnMouseRotateCameraDrag;
                @PropertiesMenu.started += instance.OnPropertiesMenu;
                @PropertiesMenu.performed += instance.OnPropertiesMenu;
                @PropertiesMenu.canceled += instance.OnPropertiesMenu;
                @DisableMouseMove.started += instance.OnDisableMouseMove;
                @DisableMouseMove.performed += instance.OnDisableMouseMove;
                @DisableMouseMove.canceled += instance.OnDisableMouseMove;
                @MouseWheelMove.started += instance.OnMouseWheelMove;
                @MouseWheelMove.performed += instance.OnMouseWheelMove;
                @MouseWheelMove.canceled += instance.OnMouseWheelMove;
                @ResetCamera.started += instance.OnResetCamera;
                @ResetCamera.performed += instance.OnResetCamera;
                @ResetCamera.canceled += instance.OnResetCamera;
            }
        }
    }
    public EditorActions @Editor => new EditorActions(this);

    // Editor-SaveMenu
    private readonly InputActionMap m_EditorSaveMenu;
    private IEditorSaveMenuActions m_EditorSaveMenuActionsCallbackInterface;
    private readonly InputAction m_EditorSaveMenu_Confirm;
    private readonly InputAction m_EditorSaveMenu_Cancel;
    private readonly InputAction m_EditorSaveMenu_MoveCursor;
    public struct EditorSaveMenuActions
    {
        private @PlayerControls m_Wrapper;
        public EditorSaveMenuActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Confirm => m_Wrapper.m_EditorSaveMenu_Confirm;
        public InputAction @Cancel => m_Wrapper.m_EditorSaveMenu_Cancel;
        public InputAction @MoveCursor => m_Wrapper.m_EditorSaveMenu_MoveCursor;
        public InputActionMap Get() { return m_Wrapper.m_EditorSaveMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(EditorSaveMenuActions set) { return set.Get(); }
        public void SetCallbacks(IEditorSaveMenuActions instance)
        {
            if (m_Wrapper.m_EditorSaveMenuActionsCallbackInterface != null)
            {
                @Confirm.started -= m_Wrapper.m_EditorSaveMenuActionsCallbackInterface.OnConfirm;
                @Confirm.performed -= m_Wrapper.m_EditorSaveMenuActionsCallbackInterface.OnConfirm;
                @Confirm.canceled -= m_Wrapper.m_EditorSaveMenuActionsCallbackInterface.OnConfirm;
                @Cancel.started -= m_Wrapper.m_EditorSaveMenuActionsCallbackInterface.OnCancel;
                @Cancel.performed -= m_Wrapper.m_EditorSaveMenuActionsCallbackInterface.OnCancel;
                @Cancel.canceled -= m_Wrapper.m_EditorSaveMenuActionsCallbackInterface.OnCancel;
                @MoveCursor.started -= m_Wrapper.m_EditorSaveMenuActionsCallbackInterface.OnMoveCursor;
                @MoveCursor.performed -= m_Wrapper.m_EditorSaveMenuActionsCallbackInterface.OnMoveCursor;
                @MoveCursor.canceled -= m_Wrapper.m_EditorSaveMenuActionsCallbackInterface.OnMoveCursor;
            }
            m_Wrapper.m_EditorSaveMenuActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Confirm.started += instance.OnConfirm;
                @Confirm.performed += instance.OnConfirm;
                @Confirm.canceled += instance.OnConfirm;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
                @MoveCursor.started += instance.OnMoveCursor;
                @MoveCursor.performed += instance.OnMoveCursor;
                @MoveCursor.canceled += instance.OnMoveCursor;
            }
        }
    }
    public EditorSaveMenuActions @EditorSaveMenu => new EditorSaveMenuActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("KeyboardMouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_ControllerSchemeIndex = -1;
    public InputControlScheme ControllerScheme
    {
        get
        {
            if (m_ControllerSchemeIndex == -1) m_ControllerSchemeIndex = asset.FindControlSchemeIndex("Controller");
            return asset.controlSchemes[m_ControllerSchemeIndex];
        }
    }
    public interface IDefaultActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnCamera(InputAction.CallbackContext context);
        void OnLayBomb(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnOpenMenu(InputAction.CallbackContext context);
        void OnDetonate(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnPickUp(InputAction.CallbackContext context);
        void OnPreviousBombType(InputAction.CallbackContext context);
        void OnNextBombType(InputAction.CallbackContext context);
    }
    public interface IEditorActions
    {
        void OnMoveXZ(InputAction.CallbackContext context);
        void OnMoveUp(InputAction.CallbackContext context);
        void OnMoveDown(InputAction.CallbackContext context);
        void OnPreviousTile(InputAction.CallbackContext context);
        void OnNextTile(InputAction.CallbackContext context);
        void OnPlaceTile(InputAction.CallbackContext context);
        void OnSaveMenu(InputAction.CallbackContext context);
        void OnHelpMenu(InputAction.CallbackContext context);
        void OnRotateCamera(InputAction.CallbackContext context);
        void OnMouseRotateCameraClick(InputAction.CallbackContext context);
        void OnMouseRotateCameraDrag(InputAction.CallbackContext context);
        void OnPropertiesMenu(InputAction.CallbackContext context);
        void OnDisableMouseMove(InputAction.CallbackContext context);
        void OnMouseWheelMove(InputAction.CallbackContext context);
        void OnResetCamera(InputAction.CallbackContext context);
    }
    public interface IEditorSaveMenuActions
    {
        void OnConfirm(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnMoveCursor(InputAction.CallbackContext context);
    }
}
